const SIGN_UP = 'SIGNUP';
const LOGIN = 'LOGIN';
const CREATE_ACCOUNT_PHONE = 'CREATEACCOUNTPHONE';
const CREATE_ACCOUNT_EMAIL = 'CREATEACCOUNTEMAIL';
const VERIFICATION_CODE = 'VERFICATIONCODE';
const PROFILE_CREATED = 'PROFILECREATED';
const COMPLETE_PAGE='COMPLETE_PAGE';